### ISSUE TITLE
Vulnerability in marked < 0.3.9

### ISSUE THREAD

**Issue by mkwhitacre** [cerner/cerner-smart-embeddable-lib#5]
Known moderate severity security vulnerability detected in marked < 0.3.9 defined in package-lock.json.

package-lock.json update suggested: marked ~> 0.3.9.

**Comment by kolkheang** [comment]
Already addressed with https://github.com/cerner/cerner-smart-embeddable-lib/pull/4.  Although, I don't think package-lock.json is needed.  Will remove it in the future.

**Comment by mjhenkes** [comment]
npm recommends that you check in into version control, so I think thats fine. https://docs.npmjs.com/files/package-lock.json

**Comment by mkwhitacre** [comment]
Cool that if it is addressed.
